In [7]:
x= [1,2,3,4,5]
print(x[:2])



[1, 2]


In [15]:
x=[1,2,3]
y=x
y[-1]=4
print(x)

[1, 2, 4]


In [17]:
for i in range(5):
    if i >= 2: break
    print(i)
for i in range(5):
    if i == 2: continue
    print(i)

0
1
0
1
3
4


In [21]:
import random
x = random.randint(0, 5)
print("x is", x)
if x > 3:
    print('too big')
elif x < 1:
    print('too small')
else:
    print('just right') 

x is 1
just right


In [24]:
a=1
def f(x):
    return x + a
def g(x,a=1):
    return x + a
print(f(1))
print(g(1))
a=2
print(f(1))
print(g(1))



2
2
3
2


In [26]:
import numpy as np
x=np.array([1,2,3])
y=x
x+=1
print(y)
x[:]=x+1
print(y)
x=x+1
print(y)
print(x)

[2 3 4]
[3 4 5]
[3 4 5]
[4 5 6]


In [29]:
class SquareClass:
    def __init__(self, length,width):
        self.length = length
        self.width = width
    def size(self):
        return self.length * self.width
square=SquareClass(2,2)
print(square.size())
   


4


In [32]:
import numpy as np
x=np.array([2,5,10,2,4])
# sort and print
print(np.sort(x))

[ 2  2  4  5 10]
